[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_RESOLUTION)s x24
autorestart=true
stdout_logfile=/tmp/xvfb.out.log
stderr_logfile=/tmp/xvfb.err.log

[program:xfce]
command=startxfce4
environment=DISPLAY=":99"
autorestart=true
stdout_logfile=/tmp/xfce.out.log
stderr_logfile=/tmp/xfce.err.log

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -nopw -forever -shared -rfbport 5900
autorestart=true
stdout_logfile=/tmp/vnc.out.log
stderr_logfile=/tmp/vnc.err.log

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 8080
autorestart=true
stdout_logfile=/tmp/novnc.out.log
stderr_logfile=/tmp/novnc.err.log

[program:lordsbot]
command=/bin/bash /home/wineuser/start.sh
environment=DISPLAY=":99"
autorestart=true
stdout_logfile=/tmp/bot.out.log
stderr_logfile=/tmp/bot.err.log
