[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_RESOLUTION)s x24
autorestart=true
user=wineuser

[program:xfce]
command=startxfce4
environment=DISPLAY=":99"
autorestart=true
user=wineuser

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -nopw -forever -shared -rfbport 5900
autorestart=true
user=wineuser

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 8080
autorestart=true
user=wineuser

[program:lordsbot]
command=/bin/bash /home/wineuser/start.sh
environment=DISPLAY=":99"
autorestart=true
user=wineuser
